<a href="https://colab.research.google.com/github/aashut-in/ML-and-DA-TRAINING/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja",
             "Rohit","Sneha","Arjun","Riya","Deepak",
             "Muskan","Yash","Komal","Abhishek","Nisha"],

    "Gender": ["Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female",
               "Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female"],

    "Age": [20,21,19,22,20,21,20,19,22,20,
            21,20,23,19,22,20,21,22,20,19],

    "Department": ["CSE","IT","ECE","CSE","IT",
                   "CSE","ECE","IT","CSE","ECE",
                   "IT","CSE","ECE","IT","CSE",
                   "ECE","IT","CSE","ECE","IT"],

    "Semester": [4,4,2,6,4,6,2,4,8,6,
                 2,8,6,4,8,2,6,4,8,2],

    "Marks": [85,92,78,95,67,88,72,91,81,76,
              69,94,73,89,97,66,82,90,79,84],

    "Attendance": [92,95,85,97,78,90,82,98,88,84,
                   80,96,83,91,99,76,89,94,87,92],

    "CGPA": [8.5,9.2,7.8,9.5,6.9,
             8.8,7.2,9.1,8.1,7.6,
             7.0,9.4,7.4,8.9,9.8,
             6.8,8.2,9.0,7.9,8.4],

    "City": ["Delhi","Lucknow","Noida","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)

print(df)

    Student_ID      Name  Gender  Age Department  Semester  Marks  Attendance  \
0          101      Aman    Male   20        CSE         4     85          92
1          102      Neha  Female   21         IT         4     92          95
2          103     Rahul    Male   19        ECE         2     78          85
3          104     Priya  Female   22        CSE         6     95          97
4          105     Karan    Male   20         IT         4     67          78
5          106    Simran  Female   21        CSE         6     88          90
6          107     Mohit    Male   20        ECE         2     72          82
7          108    Anjali  Female   19         IT         4     91          98
8          109     Vikas    Male   22        CSE         8     81          88
9          110     Pooja  Female   20        ECE         6     76          84
10         111     Rohit    Male   21         IT         2     69          80
11         112     Sneha  Female   20        CSE         8     94          96
12         113     Arjun    Male   23        ECE         6     73          83
13         114      Riya  Female   19         IT         4     89          91
14         115    Deepak    Male   22        CSE         8     97          99
15         116    Muskan  Female   20        ECE         2     66          76
16         117      Yash    Male   21         IT         6     82          89
17         118     Komal  Female   22        CSE         4     90          94
18         119  Abhishek    Male   20        ECE         8     79          87
19         120     Nisha  Female   19         IT         2     84          92

    CGPA     City
0    8.5    Delhi
1    9.2  Lucknow
2    7.8    Noida
3    9.5   Jaipur
4    6.9    Delhi
5    8.8    Noida
6    7.2  Lucknow
7    9.1    Delhi
8    8.1   Jaipur
9    7.6    Delhi
10   7.0    Noida
11   9.4  Lucknow
12   7.4    Delhi
13   8.9   Jaipur
14   9.8    Delhi
15   6.8    Noida
16   8.2  Lucknow
17   9.0    Delhi
18   7.9   Jaipur
19   8.4    Delhi

In [2]:
df.head()

,Student_ID,Name,Gender,Age,Department,Semester,Marks,Attendance,CGPA,City
0,101,Aman,Male,20,CSE,4,85,92,8.5,Delhi
1,102,Neha,Female,21,IT,4,92,95,9.2,Lucknow
2,103,Rahul,Male,19,ECE,2,78,85,7.8,Noida
3,104,Priya,Female,22,CSE,6,95,97,9.5,Jaipur
4,105,Karan,Male,20,IT,4,67,78,6.9,Delhi

In [3]:
df.head(6)

,Student_ID,Name,Gender,Age,Department,Semester,Marks,Attendance,CGPA,City
0,101,Aman,Male,20,CSE,4,85,92,8.5,Delhi
1,102,Neha,Female,21,IT,4,92,95,9.2,Lucknow
2,103,Rahul,Male,19,ECE,2,78,85,7.8,Noida
3,104,Priya,Female,22,CSE,6,95,97,9.5,Jaipur
4,105,Karan,Male,20,IT,4,67,78,6.9,Delhi
5,106,Simran,Female,21,CSE,6,88,90,8.8,Noida

In [4]:
df.shape

(20, 10)

In [6]:
df.sample()

,Student_ID,Name,Gender,Age,Department,Semester,Marks,Attendance,CGPA,City
18,119,Abhishek,Male,20,ECE,8,79,87,7.9,Jaipur

In [7]:
df["Marks"].max()

97

In [8]:
df["Marks"].mean()

np.float64(82.4)

In [9]:
df["Marks"].sum()

np.int64(1648)

In [10]:
df["Gender"].count()

np.int64(20)

In [11]:
df["Department"].unique()

array(['CSE', 'IT', 'ECE'], dtype=object)

In [12]:
df["Department"].nunique()

3

In [13]:
df.rename(columns = {"Name" : "Stu_Name"})

,Student_ID,Stu_Name,Gender,Age,Department,Semester,Marks,Attendance,CGPA,City
0,101,Aman,Male,20,CSE,4,85,92,8.5,Delhi
1,102,Neha,Female,21,IT,4,92,95,9.2,Lucknow
2,103,Rahul,Male,19,ECE,2,78,85,7.8,Noida
3,104,Priya,Female,22,CSE,6,95,97,9.5,Jaipur
4,105,Karan,Male,20,IT,4,67,78,6.9,Delhi
5,106,Simran,Female,21,CSE,6,88,90,8.8,Noida
6,107,Mohit,Male,20,ECE,2,72,82,7.2,Lucknow
7,108,Anjali,Female,19,IT,4,91,98,9.1,Delhi
8,109,Vikas,Male,22,CSE,8,81,88,8.1,Jaipur
9,110,Pooja,Female,20,ECE,6,76,84,7.6,Delhi
10,111,Rohit,Male,21,IT,2,69,80,7.0,Noida
11,112,Sneha,Female,20,CSE,8,94,96,9.4,Lucknow
12,113,Arjun,Male,23,ECE,6,73,83,7.4,Delhi
13,114,Riya,Female,19,IT,4,89,91,8.9,Jaipur
14,115,Deepak,Male,22,CSE,8,97,99,9.8,Delhi
15,116,Muskan,Female,20,ECE,2,66,76,6.8,Noida
16,117,Yash,Male,21,IT,6,82,89,8.2,Lucknow
17,118,Komal,Female,22,CSE,4,90,94,9.0,Delhi
18,119,Abhishek,Male,20,ECE,8,79,87,7.9,Jaipur
19,120,Nisha,Female,19,IT,2,84,92,8.4,Delhi

In [19]:
df.isnull()
df.isnull().sum()

Student_ID    0
Name          0
Gender        0
Age           0
Department    0
Semester      0
Marks         0
Attendance    0
CGPA          0
City          0
dtype: int64

In [14]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool