<a href="https://colab.research.google.com/github/aashut-in/ML-and-DA-TRAINING/blob/main/Py1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#INTRODUCTION TO PYTHON
"""Python: Easy to understand, useful libraries. OOP. Guido Van Rossum"""

print("Hello world!")
print("Amber")

Hello world!
Amber

In [ ]:
#OPERATORS

a = 100
b = 30

print(f"Variables: a = {a}, b = {b}\n")

print("--- Arithmetic Operators ---")
print(f"Sum (a + b): {a + b}")
print(f"Difference (a - b): {a - b}")
print(f"Product (a * b): {a * b}")
print(f"Quotient (a / b): {a / b}")
print(f"Floor Division (a // b): {a // b}")
print(f"Remainder (a % b): {a % b}")
print(f"Exponent (a ** 2): {a ** 2}\n")

print("--- Comparison Operators ---")
print(f"Equal (a == b): {a == b}")
print(f"Not Equal (a != b): {a != b}")
print(f"Greater Than (a > b): {a > b}")
print(f"Less Than (a < b): {a < b}")
print(f"Greater Than or Equal To (a >= b): {a >= b}")
print(f"Less Than or Equal To (a <= b): {a <= b}")

Variables: a = 100, b = 30

--- Arithmetic Operators ---
Sum (a + b): 130
Difference (a - b): 70
Product (a * b): 3000
Quotient (a / b): 3.3333333333333335
Floor Division (a // b): 3
Remainder (a % b): 10
Exponent (a ** 2): 10000

--- Comparison Operators ---
Equal (a == b): False
Not Equal (a != b): True
Greater Than (a > b): True
Less Than (a < b): False
Greater Than or Equal To (a >= b): True
Less Than or Equal To (a <= b): False

In [ ]:
# DATATYPES

# Integer (int): Represents whole numbers, positive or negative.
a = 12
print(f"Type of a: {type(a)}")

# String (str): Represents sequences of characters.
b = "yay"
print(f"Type of b: {type(b)}")

# Float (float): Represents real numbers with floating-point precision.
c = 10.00
print(f"Type of c: {type(c)}")

# Boolean (bool): Represents truth values (True or False).
d = True
print(f"Type of d: {type(d)}")

# List (list): An ordered, mutable collection of items.
my_list = [1, 2, 3, "hello"]
print(f"Type of my_list: {type(my_list)}")

# Tuple (tuple): An ordered, immutable collection of items.
my_tuple = (1, 2, "world")
print(f"Type of my_tuple: {type(my_tuple)}")

# Dictionary (dict): An unordered collection of key-value pairs.
my_dict = {"name": "Daisy"}
print(f"Type of my_dict: {type(my_dict)}")

# Set (set): An unordered collection of unique items.
my_set = {1, 2, 3, 3, 4}
print(f"Type of my_set: {type(my_set)}")

Type of a: <class 'int'>
Type of b: <class 'str'>
Type of c: <class 'float'>
Type of d: <class 'bool'>
Type of my_list: <class 'list'>
Type of my_tuple: <class 'tuple'>
Type of my_dict: <class 'dict'>
Type of my_set: <class 'set'>

In [ ]:
#TAKING INPUTS

name = input("What is your name? ")
age = input("How old are you? ")
phone = input("What is your phone number? ")
dept = input("What is your department? ")
print(f"Hello, {name}!")
print(f"You are {age} years old.")
print(f"Your phone number is {phone}.")
print(f"Your department is {dept}.")

What is your name? Amber
How old are you? 18
What is your phone number? XXXXXXXX09
What is your department? CSE AL
Hello, Amber!
You are 18 years old.
Your phone number is XXXXXXXX09.
Your department is CSE AL.

In [ ]:
# TYPECASTING - Changing data types!

# --- Implicit Typecasting (Automatic) ---
# Python changes types for you, like when adding int and float.
int_num = 10
float_num = 5.5
result_add = int_num + float_num # int_num became a float here!
print(f"Implicit (int + float): {int_num} + {float_num} = {result_add} (result type: {type(result_add).__name__})\n")

# --- Explicit Typecasting (Manual) ---
# We use functions like int(), float(), str() to change types.

# 1. To Int (int())
str_to_int = "123"
print(f"Str to Int: '{str_to_int}' becomes {int(str_to_int)}")
float_to_int = 10.75
print(f"Float to Int: {float_to_int} becomes {int(float_to_int)} (chops off decimal)\n")

# 2. To Float (float())
int_to_float = 50
print(f"Int to Float: {int_to_float} becomes {float(int_to_float)}")
str_to_float = "98.6"
print(f"Str to Float: '{str_to_float}' becomes {float(str_to_float)}\n")

# 3. To Str (str())
int_to_str = 100
print(f"Int to Str: {int_to_str} becomes '{str(int_to_str)}'")
bool_to_str = True
print(f"Bool to Str: {bool_to_str} becomes '{str(bool_to_str)}'\n")

# 4. To Bool (bool())
# 0, empty strings/lists, etc., are False. Others are True.
print(f"bool(0) is {bool(0)}")
print(f"bool(1) is {bool(1)}")
print(f"bool('') is {bool('')}")
print(f"bool('hello') is {bool('hello')}")
print(f"bool([]) is {bool([])}")
print(f"bool([1]) is {bool([1])}\n")

# 5. To List (list())
str_to_list = "Python"
print(f"Str to List: '{str_to_list}' becomes {list(str_to_list)}")
tuple_to_list = (1, 2, 3)
print(f"Tuple to List: {tuple_to_list} becomes {list(tuple_to_list)}\n")

# 6. To Tuple (tuple())
list_to_tuple = [4, 5, 6]
print(f"List to Tuple: {list_to_tuple} becomes {tuple(list_to_tuple)}")
str_to_tuple = "abc"
print(f"Str to Tuple: '{str_to_tuple}' becomes {tuple(str_to_tuple)}\n")

# 7. To Set (set())
list_to_set = [1, 2, 2, 3, 4]
# Sets remove duplicates!
print(f"List to Set: {list_to_set} becomes {set(list_to_set)}")
str_to_set = "banana"
print(f"Str to Set: '{str_to_set}' becomes {set(str_to_set)}\n")

Implicit (int + float): 10 + 5.5 = 15.5 (result type: float)

Str to Int: '123' becomes 123
Float to Int: 10.75 becomes 10 (chops off decimal)

Int to Float: 50 becomes 50.0
Str to Float: '98.6' becomes 98.6

Int to Str: 100 becomes '100'
Bool to Str: True becomes 'True'

bool(0) is False
bool(1) is True
bool('') is False
bool('hello') is True
bool([]) is False
bool([1]) is True

Str to List: 'Python' becomes ['P', 'y', 't', 'h', 'o', 'n']
Tuple to List: (1, 2, 3) becomes [1, 2, 3]

List to Tuple: [4, 5, 6] becomes (4, 5, 6)
Str to Tuple: 'abc' becomes ('a', 'b', 'c')

List to Set: [1, 2, 2, 3, 4] becomes {1, 2, 3, 4}
Str to Set: 'banana' becomes {'n', 'b', 'a'}

In [ ]:
#STRING FUNCTIONS

a = "abcdef"
print(f"{a.upper()}")
b = "GHIJKS"
print(f"{b.lower()}")
print(f"{len(a)}")

ABCDEF
ghijks
6

In [ ]:
#Basic if-else program
age = int(input("Enter your age: "))
if age >= 18:
  print("Eligible to vote.")
else:
  print("Not eligible to vote.")

Enter your age: 18
Eligible to vote.

In [ ]:
#DIVISION BY 5 and 3
n = int(input("Enter a number: "))
if n % 5 == 0 and n % 3 == 0 :
  print(f"{n} is divisble both by 3 and 5.")
elif n % 5 ==0 :
  print(f"{n} is divisible by 5.")
elif n % 3 == 0 :
  print(f"{n} is divisible by 3.")
else :
  print(f"{n} is NOT divisible both by 3 and 5.")

Enter a number: 30
30 is divisble both by 3 and 5.

In [ ]:
#ATM WITHDRAWAL
bal = 100000.00
amt = float(input("Enter the amount to withdraw: "))
if amt <= bal :
  print(f"Transactionable.")
else :
  printt(f"Insufficient Balance.")

Enter the amount to withdraw: 45000
Transactionable.

In [ ]:
#SINGLE DIGIT NUMBER
n = int(input("Enter a new number: "))
if len(str(n)) == 1 :
  print(f"{n} is single digit.")
else :
  print("NOT single digit.")

Enter a new number: -9
9 is single digit.

In [ ]:
#NEGATIVE NUMBER
n = int(input("Enter a new number: "))
m = n
if m < 0 :
  m = n * (-1)
if True :
  print(f"{n} is {len(str(m))} digit.")
else :
  print(f"NA")

Enter a new number: 310605
310605 is 6 digit.

In [ ]:
#NO OF DIGITS
n = float((input("Enter a new number: ")))
temp = n
c = 0
while temp != 0 :
  ld = temp % 10
  temp = temp // 10
  c += 1
print(c)

Enter a new number: 100
3

In [ ]:
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        return "Error! Division by zero."
    return x / y

print("Select operation:")
print("1. Add")
print("2. Subtract")
print("3. Multiply")
print("4. Divide")

while True:
    choice = input("Enter choice(1/2/3/4): ")

    if choice in ('1', '2', '3', '4'):
        try:
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
        except ValueError:
            print("Invalid input. Please enter numbers only!")
            continue

        if choice == '1':
            print(f"{num1} + {num2} = {add(num1, num2)}")
        elif choice == '2':
            print(f"{num1} - {num2} = {subtract(num1, num2)}")
        elif choice == '3':
            print(f"{num1} * {num2} = {multiply(num1, num2)}")
        elif choice == '4':
            print(f"{num1} / {num2} = {divide(num1, num2)}")

        next_calculation = input("Let's do next calculation? (yes/no): ")
        if next_calculation.lower() == "no":
            break
    else:
        print("Invalid Input")

In [ ]:
#STRING FUNCTIONS
name = "Amber Heart"
print(name.split())
print(name.find('t'))
print(name.count('e'))
print(len(name))

['Amber', 'Heart']
10
2
11

In [ ]:
#LIST OPERATIONS
a = [10, 20, 30]
b = [20, 30, 50, 60]
print(a.sort())
print(a + b)
print(a[0])
print(a[0:3])
print((a+b)[::-1])
print(b.reverse())
print(a.count(10))
print(a.clear())
print(a)

None
[10, 20, 30, 20, 30, 50, 60]
10
[10, 20, 30]
[60, 50, 30, 20, 30, 20, 10]
None
1
None
[]

In [ ]:
import math
a = 4
print(math.sqrt(a))

2.0

In [ ]:
#DATA ANALYTICS
import pandas as pd
pd.read_csv('/content/Zomato-data-.csv')

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [8]:
#one dimensional data
import pandas as pd
marks = pd.Series([85,90,78,95])
print (marks)

0    85
1    90
2    78
3    95
dtype: int64

In [9]:
#2-D DATA
student = {
    "Name" : ['Rahul', 'Amit', 'Priya'],
    "Age" : [20, 21, 19],
    "Marks" : [80, 90, 95]
    }
df = pd.DataFrame(student)
df

    Name  Age  Marks
0  Rahul   20     80
1   Amit   21     90
2  Priya   19     95

In [10]:
df = pd.read_csv('/content/Zomato-data-.csv')
#df = pd.read_csv(r"")

In [13]:
df.to_csv("output.csv") #saving to csv

In [18]:
#FUNCTIONS
'''df.head() #first five rows
df.head(5)

df.tail() #lowest five rows

df.sample() #random values

df.shape #rows and column

df.columns #name of columns'''

'df.head() #first five rows\ndf.head(5)\n\ndf.tail() #lowest five rows\n\ndf.sample() #random values\n\ndf.shape #rows and column\n\ndf.columns #name of columns'

In [11]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [14]:
df.shape

(148, 7)

In [15]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [19]:
df.sample()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
70,The Good Bowl,Yes,No,3.6/5,6,500,Dining

In [20]:
df.dtypes

name                           object
online_order                   object
book_table                     object
rate                           object
votes                           int64
approx_cost(for two people)     int64
listed_in(type)                object
dtype: object

In [21]:
df['approx_cost(for two people)'].describe()

count    148.000000
mean     418.243243
std      223.085098
min      100.000000
25%      200.000000
50%      400.000000
75%      600.000000
max      950.000000
Name: approx_cost(for two people), dtype: float64

In [24]:
df["name"] #selecting single column
df[["name", "online_order"]] #selecting multiple column data

                      name online_order
0                    Jalsa          Yes
1           Spice Elephant          Yes
2          San Churro Cafe          Yes
3    Addhuri Udupi Bhojana           No
4            Grand Village           No
..                     ...          ...
143       Melting Melodies           No
144        New Indraprasta           No
145           Anna Kuteera          Yes
146                 Darbar           No
147          Vijayalakshmi          Yes

[148 rows x 2 columns]

In [ ]:
df.sort_values("Salary") #ascending order
#df["votes"] This column does not exist in the current DataFrame

In [ ]:
"""
df.sort_values("votes",ascending=False) #descending order

df.sort_values(["Department","Salary"]) #mulriple column sorting

df["Bonus"]= df["Salary"]*0.18  #adding new column

df["Total Salary"]=df["Salary"]+df["Bonus"]  #adding new column
"""

In [25]:
import pandas as pd

data = {
    "Emp_ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja"],
    "Age": [24,25,23,28,30,26,27,24,29,25],
    "Department": ["HR","IT","Sales","IT","HR",
                   "Finance","Sales","IT","Finance","HR"],
    "Salary": [35000,50000,45000,60000,38000,
               55000,47000,62000,58000,40000],
    "City": ["Delhi","Lucknow","Noida","Delhi","Jaipur",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)

print(df)

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   38000   Jaipur
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [26]:
df.head()

   Emp_ID   Name  Age Department  Salary     City
0     101   Aman   24         HR   35000    Delhi
1     102   Neha   25         IT   50000  Lucknow
2     103  Rahul   23      Sales   45000    Noida
3     104  Priya   28         IT   60000    Delhi
4     105  Karan   30         HR   38000   Jaipur

In [27]:
df.tail()

   Emp_ID    Name  Age Department  Salary     City
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [28]:
df.sample()

   Emp_ID  Name  Age Department  Salary     City
1     102  Neha   25         IT   50000  Lucknow

In [30]:
df.shape

(10, 6)

In [31]:
df.columns

Index(['Emp_ID', 'Name', 'Age', 'Department', 'Salary', 'City'], dtype='object')

In [32]:
df.info

<bound method DataFrame.info of    Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   38000   Jaipur
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi>

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
 5   City        10 non-null     object
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [34]:
df.describe()

          Emp_ID        Age        Salary
count   10.00000  10.000000     10.000000
mean   105.50000  26.100000  49000.000000
std      3.02765   2.330951   9580.071909
min    101.00000  23.000000  35000.000000
25%    103.25000  24.250000  41250.000000
50%    105.50000  25.500000  48500.000000
75%    107.75000  27.750000  57250.000000
max    110.00000  30.000000  62000.000000

In [35]:
df.dtypes

Emp_ID         int64
Name          object
Age            int64
Department    object
Salary         int64
City          object
dtype: object

In [36]:
df["Name"]

0      Aman
1      Neha
2     Rahul
3     Priya
4     Karan
5    Simran
6     Mohit
7    Anjali
8     Vikas
9     Pooja
Name: Name, dtype: object

In [38]:
df[["Name", "Salary"]]

     Name  Salary
0    Aman   35000
1    Neha   50000
2   Rahul   45000
3   Priya   60000
4   Karan   38000
5  Simran   55000
6   Mohit   47000
7  Anjali   62000
8   Vikas   58000
9   Pooja   40000

In [39]:
df[df["Salary"] > 5000]

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   38000   Jaipur
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [40]:
df[df["Department"] == 'IT']

   Emp_ID    Name  Age Department  Salary     City
1     102    Neha   25         IT   50000  Lucknow
3     104   Priya   28         IT   60000    Delhi
7     108  Anjali   24         IT   62000    Delhi

In [41]:
df[df["Age"] == 25]

   Emp_ID   Name  Age Department  Salary     City
1     102   Neha   25         IT   50000  Lucknow
9     110  Pooja   25         HR   40000    Delhi

In [43]:
df[(df["Salary"] > 5000) & (df["Department"] == "IT")]

   Emp_ID    Name  Age Department  Salary     City
1     102    Neha   25         IT   50000  Lucknow
3     104   Priya   28         IT   60000    Delhi
7     108  Anjali   24         IT   62000    Delhi

In [44]:
df.sort_values("Salary")

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
4     105   Karan   30         HR   38000   Jaipur
9     110   Pooja   25         HR   40000    Delhi
2     103   Rahul   23      Sales   45000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
1     102    Neha   25         IT   50000  Lucknow
5     106  Simran   26    Finance   55000    Noida
8     109   Vikas   29    Finance   58000   Jaipur
3     104   Priya   28         IT   60000    Delhi
7     108  Anjali   24         IT   62000    Delhi

In [45]:
df.sort_values("Salary", ascending = False)

   Emp_ID    Name  Age Department  Salary     City
7     108  Anjali   24         IT   62000    Delhi
3     104   Priya   28         IT   60000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
5     106  Simran   26    Finance   55000    Noida
1     102    Neha   25         IT   50000  Lucknow
6     107   Mohit   27      Sales   47000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
9     110   Pooja   25         HR   40000    Delhi
4     105   Karan   30         HR   38000   Jaipur
0     101    Aman   24         HR   35000    Delhi

In [46]:
df["Salary"].max()

62000

In [47]:
df["Salary"].min()

35000

In [48]:
df["Salary"].mean()

np.float64(49000.0)

In [49]:
df["Salary"].sum()

np.int64(490000)

In [50]:
df["Name"].count()

np.int64(10)

In [51]:
df["Department"].unique()

array(['HR', 'IT', 'Sales', 'Finance'], dtype=object)

In [53]:
df["Department"].nunique()

4

In [56]:
df["Bonus"] = df["Salary"]*0.5
df

   Emp_ID    Name  Age Department  Salary     City    Bonus
0     101    Aman   24         HR   35000    Delhi  17500.0
1     102    Neha   25         IT   50000  Lucknow  25000.0
2     103   Rahul   23      Sales   45000    Noida  22500.0
3     104   Priya   28         IT   60000    Delhi  30000.0
4     105   Karan   30         HR   38000   Jaipur  19000.0
5     106  Simran   26    Finance   55000    Noida  27500.0
6     107   Mohit   27      Sales   47000  Lucknow  23500.0
7     108  Anjali   24         IT   62000    Delhi  31000.0
8     109   Vikas   29    Finance   58000   Jaipur  29000.0
9     110   Pooja   25         HR   40000    Delhi  20000.0

In [57]:
df.rename(columns = {"Name" : "Emp_name"})

   Emp_ID Emp_name  Age Department  Salary     City    Bonus
0     101     Aman   24         HR   35000    Delhi  17500.0
1     102     Neha   25         IT   50000  Lucknow  25000.0
2     103    Rahul   23      Sales   45000    Noida  22500.0
3     104    Priya   28         IT   60000    Delhi  30000.0
4     105    Karan   30         HR   38000   Jaipur  19000.0
5     106   Simran   26    Finance   55000    Noida  27500.0
6     107    Mohit   27      Sales   47000  Lucknow  23500.0
7     108   Anjali   24         IT   62000    Delhi  31000.0
8     109    Vikas   29    Finance   58000   Jaipur  29000.0
9     110    Pooja   25         HR   40000    Delhi  20000.0

In [ ]:
df.drop("Bonus",axis=1,inplace=True,errors = 'ignore')
df

   Emp_ID Emp_name  Age Department
0     101     Aman   24         HR
1     102     Neha   25         IT
2     103    Rahul   23      Sales
3     104    Priya   28         IT
4     105    Karan   30         HR
5     106   Simran   26    Finance
6     107    Mohit   27      Sales
7     108   Anjali   24         IT
8     109    Vikas   29    Finance
9     110    Pooja   25         HR

In [ ]:
df.drop("Bonus",axis=1,inplace=True,errors = 'ignore')
df

   Emp_ID Emp_name  Age Department
0     101     Aman   24         HR
1     102     Neha   25         IT
2     103    Rahul   23      Sales
3     104    Priya   28         IT
4     105    Karan   30         HR
5     106   Simran   26    Finance
6     107    Mohit   27      Sales
7     108   Anjali   24         IT
8     109    Vikas   29    Finance
9     110    Pooja   25         HR

In [ ]:
df.drop("City",axis=1,inplace = True,errors = 'ignore')
df

   Emp_ID Emp_name  Age Department
0     101     Aman   24         HR
1     102     Neha   25         IT
2     103    Rahul   23      Sales
3     104    Priya   28         IT
4     105    Karan   30         HR
5     106   Simran   26    Finance
6     107    Mohit   27      Sales
7     108   Anjali   24         IT
8     109    Vikas   29    Finance
9     110    Pooja   25         HR

In [58]:
df.isnull().sum()

Emp_ID        0
Name          0
Age           0
Department    0
Salary        0
City          0
Bonus         0
dtype: int64

In [59]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [60]:
df.duplicated().sum()

np.int64(0)

In [61]:
df[df['City']] = 'Delhi'
df

,Emp_ID,Name,Age,Department,Salary,City,Bonus,Delhi,Lucknow,Noida,Jaipur
0,101,Aman,24,HR,35000,Delhi,17500.0,Delhi,Delhi,Delhi,Delhi
1,102,Neha,25,IT,50000,Lucknow,25000.0,Delhi,Delhi,Delhi,Delhi
2,103,Rahul,23,Sales,45000,Noida,22500.0,Delhi,Delhi,Delhi,Delhi
3,104,Priya,28,IT,60000,Delhi,30000.0,Delhi,Delhi,Delhi,Delhi
4,105,Karan,30,HR,38000,Jaipur,19000.0,Delhi,Delhi,Delhi,Delhi
5,106,Simran,26,Finance,55000,Noida,27500.0,Delhi,Delhi,Delhi,Delhi
6,107,Mohit,27,Sales,47000,Lucknow,23500.0,Delhi,Delhi,Delhi,Delhi
7,108,Anjali,24,IT,62000,Delhi,31000.0,Delhi,Delhi,Delhi,Delhi
8,109,Vikas,29,Finance,58000,Jaipur,29000.0,Delhi,Delhi,Delhi,Delhi
9,110,Pooja,25,HR,40000,Delhi,20000.0,Delhi,Delhi,Delhi,Delhi